language: node_js
node_js:
  - '8'
branches:
  only:
    - master
deploy:
  provider: npm
  email: barlockm@gmail.com
  api_key:
    secure: PbQt7nedejcNpePz67XMSmGxFKNFIPDrvcVKtrhgUKJFTsL8Yg3FY+Xosn5Zoz4uqG7ayC664IR1cywg+x+gjDdwu/LW3FwllqVpsdtbp360agzYrRTOs257lH6VFCy+EAOemXxmaDEOST115E9ron6UtK54P9BKyDR9Qg9tUHVPzKcL6OT3DdDan3uDUY+TLAo+M7hT9dqb2qx2oh4XVvy9O+NqytsmEgSyo4PboieeJk01MM/j9EaCZWU2fJnv7eX3CZfR2j+9fwemP9kPeCuK4UkeGe1PcFLj3HMtiHwHw+rCcnih9R/ZYAZXck9OVxqsnadorGSYK9FLrGwEIloLaAcak3wo8xBizvFEYAlPjJyPdzSVo+2tO42znUXpq4cT97+ba/tEQbTbaQj/55TsQH0v3tTJ7lZX8/lJRmCIzauRv8z2/DdZYQ/pi2rq82vkjV3ovp9oI2dmA7U4hun+WHXApSSFIgALf3fooTxrFZr6r9y0s/Nhjp7SNssmhCz+kO3pt+El+rI0OOsfTHm/Nef+2e2GMUmKMOzYeAtKZGeycQVecunpsmxdhmj91An2CIUvZtICsAtJ3Vm1K938A6YhCW5um8GDjzn479idydX1KYi41Cxy7RQheDd0mPxm1elz9zq/OH9nCTD4fDgh7SUEHsACMsG1EpdF8rI=
  on:
    tags: true
    repo: ConsenSys/eslint-config-web3studio
